name: portfolio_vinidev
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.4.0
  scrollable_positioned_list: 0.3.5
  get_it: ^7.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/cv/
    - assets/images/dash/
    - assets/images/projects/
    - assets/images/logo/

  fonts:
    - family: Compiler
      fonts:
        - asset: assets/fonts/compiler/Fontspring-DEMO-compiler-black.otf
          weight: 900
        - asset: assets/fonts/compiler/Fontspring-DEMO-compiler-blackitalic.otf
          weight: 900
          style: italic
        - asset: assets/fonts/compiler/Fontspring-DEMO-compiler-extrabold.otf
          weight: 800
        - asset: assets/fonts/compiler/Fontspring-DEMO-compiler-extrabolditalic.otf
          weight: 800
          style: italic
        - asset: assets/fonts/compiler/Fontspring-DEMO-compiler-bold.otf
          weight: 700
        - asset: assets/fonts/compiler/Fontspring-DEMO-compilerplain-medium.otf
          weight: 400
        
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/comfortaa/Comfortaa-Regular.ttf
        - asset: assets/fonts/comfortaa/Comfortaa-Light.ttf
          weight: 100
        - asset: assets/fonts/comfortaa/Comfortaa-Medium.ttf
          weight: 500
        - asset: assets/fonts/comfortaa/Comfortaa-SemiBold.ttf
          weight: 800
        - asset: assets/fonts/comfortaa/Comfortaa-Bold.ttf
          weight: 900        
